artifacts_roots: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset: "apollo2506/eurosat-dataset"
  local_data_file: artifacts/data_ingestion/eurosat-dataset.zip
  unzip_dir: artifacts/data_ingestion

